name: Deploy react app to github pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config/node/frontend
    steps:
      - name: Sprawdzenie
        uses: actions/checkout@v4

      - name: Przygotuj Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instaluj zależności Python
        run: pip install pandas openpyxl
        working-directory: config/node/backend

      - name: Konwertuj Excel na JSON
        run: python convertJson.py
        working-directory: config/node/backend

      - name: Przygotuj Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: config/node/frontend/package-lock.json

      - name: Instaluj zaleznosci
        run: npm install

      - name: Zkompiluj
        run: npm run build

      - name: Wrzuc artefakty
        uses: actions/upload-pages-artifact@v3
        with:
          path: config/node/frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Wrzucenie na github pages
        id: deployment
        uses: actions/deploy-pages@v4
